import type { Locale } from "@/i18n/config";

const content = {
  en: {
    hero: { eyebrow: "NURAA · The scent of home", title: "Luxury Arabian Home Fragrance", body: "Fragrances made for generous homes, shared tables and the moments that stay with us.", primary: "Discover the collections", secondary: "Our story" },
    story: { eyebrow: "Our heritage", title: "The Essence of Arabian Homes", body: "In Arabian homes, fragrance is a language of welcome. Oud is lit before guests arrive, coffee is poured, and familiar rooms become the setting for moments shared across generations.", body2: "NURAA carries this tradition forward through scents composed for contemporary Saudi life — warm, refined and always rooted in home.", pillars: [["Arabian hospitality", "A beautiful welcome begins before a word is spoken."], ["The oud tradition", "Precious woods connect memory, place and ritual."], ["Family moments", "Fragrance becomes part of the stories a home holds."]], cta: "Read the NURAA story" },
    collections: { eyebrow: "Three expressions of home", title: "The NURAA Collections", body: "From the depth of oud to the softness of rose and amber after dark.", items: [["Desert Oud", "Oud · Cedarwood · Smoked Amber", "Deep and grounding, composed for the evening majlis."], ["Rose Garden", "Taif Rose · Jasmine · Soft Musk", "A luminous floral inspired by gardens after the rain."], ["Amber Night", "Amber · Cardamom · Cashmere Wood", "A golden, enveloping trail for evenings shared at home."]] },
    ritual: { eyebrow: "Fragrance through the day", title: "A Ritual for Every Hour", body: "Scent moves with the rhythm of your home — fresh in the morning, soft through the afternoon, and deep as family gathers at night.", items: [["Morning", "Open the home", "Bright amber and bergamot welcome clarity and a new beginning."], ["Afternoon", "Make space to pause", "Rose and soft musk settle into moments of conversation and calm."], ["Evening", "Gather in warmth", "Oud and woods create a generous atmosphere for those you welcome home."]] },
    best: { eyebrow: "Objects of fragrance", title: "For your home", body: "Signature scents and beautifully considered forms for everyday rituals.", all: "Shop all fragrances", shop: "Discover" },
    gifts: { eyebrow:"The art of giving",title:"Made for Meaningful Moments",body:"A fragrant gesture for the celebrations, welcomes and new beginnings held close in Saudi homes.",items:[["Ramadan","For evenings of reflection and gathering."],["Eid","A generous expression of joy."],["Wedding","A lasting scent for a new chapter."],["New Home","The first fragrance of a new place."]],cta:"Explore gifts" },
    trust: [["Rooted in Arabia", "Compositions inspired by oud culture and Saudi homes."], ["Made for living", "Elegant fragrances designed to sit naturally in daily life."], ["A beautiful welcome", "Carefully packed and delivered throughout the Kingdom."]],
  },
  ar: {
    hero: { eyebrow: "نُـورا · عطر البيت", title: "عطور منزلية عربية فاخرة", body: "عطور صُممت للبيوت الكريمة، والموائد المشتركة، واللحظات التي تبقى معنا.", primary: "اكتشفوا المجموعات", secondary: "قصتنا" },
    story: { eyebrow: "إرثنا", title: "روح البيوت العربية", body: "في البيوت العربية، العطر لغة للترحيب. يُشعل العود قبل وصول الضيوف، وتُصب القهوة، وتصبح الغرف المألوفة مسرحاً للحظات تتشاركها الأجيال.", body2: "تحمل نُـورا هذا الإرث إلى الحياة السعودية المعاصرة بعطور دافئة وراقية، جذورها دائماً في البيت.", pillars: [["الضيافة العربية", "يبدأ الترحيب الجميل قبل أن تُقال أول كلمة."], ["إرث العود", "أخشاب نفيسة تصل الذاكرة بالمكان والطقوس."], ["لحظات العائلة", "يصبح العطر جزءاً من الحكايات التي يحتفظ بها البيت."]], cta: "اقرؤوا قصة نُـورا" },
    collections: { eyebrow: "ثلاثة تعبيرات عن البيت", title: "مجموعات نُـورا", body: "من عمق العود إلى نعومة الورد والعنبر بعد حلول المساء.", items: [["عود الصحراء", "عود · خشب الأرز · عنبر مدخّن", "عطر عميق للمجلس وأمسياته."], ["حديقة الورد", "ورد طائفي · ياسمين · مسك ناعم", "زهور مضيئة مستوحاة من الحدائق بعد المطر."], ["عنبر الليل", "عنبر · هيل · خشب الكشمير", "أثر ذهبي يحتضن أمسيات البيت."]] },
    ritual: { eyebrow: "العطر على امتداد اليوم", title: "طقس لكل ساعة", body: "يتحرك العطر مع إيقاع البيت — منعشاً في الصباح، ناعماً بعد الظهر، وعميقاً حين تجتمع العائلة مساءً.", items: [["الصباح", "افتحوا البيت للنور", "عنبر مشرق وبرغموت لبداية صافية."], ["بعد الظهر", "لحظة للهدوء", "ورد ومسك ناعم لأحاديث هادئة."], ["المساء", "اجتمعوا على الدفء", "العود والأخشاب يصنعان أجواء كريمة لمن تحبون."]] },
    best: { eyebrow: "قطع عطرية", title: "لبيتكم", body: "عطور مميزة وأشكال مدروسة لطقوس كل يوم.", all: "تسوقوا جميع العطور", shop: "اكتشفوا" },
    gifts: { eyebrow:"فن الإهداء",title:"للحظات ذات المعنى",body:"لفتة عطرية للاحتفالات والبدايات واللقاءات التي تحتفظ بها البيوت السعودية.",items:[["رمضان","لأمسيات التأمل والاجتماع."],["العيد","تعبير كريم عن الفرح."],["الزفاف","عطر باقٍ لفصل جديد."],["البيت الجديد","أول عطر لمكان جديد."]],cta:"اكتشفوا الهدايا" },
    trust: [["جذور عربية", "تركيبات مستوحاة من ثقافة العود والبيوت السعودية."], ["صُممت للحياة", "عطور راقية تنسجم ببساطة مع تفاصيل اليوم."], ["ترحيب جميل", "تغليف بعناية وتوصيل إلى جميع أنحاء المملكة."]],
  },
} as const;

export function getBrandContent(locale: Locale) { return content[locale]; }
