export type Product = {
  slug: string; price: number; compareAtPrice?: number; image: string; tag?: "new" | "bestseller";
  en: { name: string; category: string; description: string; benefits: string[]; usage: string };
  ar: { name: string; category: string; description: string; benefits: string[]; usage: string };
};

export const products: Product[] = [
  { slug: "sahar-perfume-oil", price: 189, image: "/images/brand-v2/collection-morning-amber.png", en: { name: "Sahar Perfume Oil", category: "Fragrance", description: "A warm, luminous perfume oil with amber, soft musk and a trace of saffron. Made to sit close to the skin and unfold slowly.", benefits: ["Alcohol-free concentrated oil", "Travel-friendly roll-on", "Long-wearing, intimate scent"], usage: "Roll gently over pulse points—wrists, neck and behind the ears." }, ar: { name: "زيت عطر سَحَر", category: "عطور", description: "زيت عطري دافئ ومشرق بنفحات العنبر والمسك الناعم ولمسة من الزعفران، يتطور بهدوء على البشرة.", benefits: ["زيت مركز خالٍ من الكحول", "عبوة عملية للسفر", "رائحة حميمة تدوم طويلاً"], usage: "مرّريه برفق على نقاط النبض عند المعصم والرقبة وخلف الأذنين." } },
  { slug: "rose-quartz-ritual-set", price: 149, image: "/images/brand-v2/collection-rose-garden.png", en: { name: "Rose Garden Home Fragrance", category: "Home Fragrance", description: "A luminous composition of Taif rose, jasmine and soft musk, created for welcoming rooms.", benefits: ["Balanced floral composition", "Made for shared living spaces", "Presented in NURAA gift packaging"], usage: "Mist lightly into the room from a distance and allow the fragrance to settle." }, ar: { name: "عطر المنزل حديقة الورد", category: "عطور منزلية", description: "تركيبة مشرقة من الورد الطائفي والياسمين والمسك الناعم صُممت لأجواء الترحيب.", benefits: ["تركيبة زهرية متوازنة", "مناسبة للمجالس والمساحات المشتركة", "تُقدم في تغليف نورا المميز"], usage: "رشي العطر بخفة في الغرفة من مسافة واتركيه يستقر في المكان." } },
  { slug: "quiet-oud-diffuser", price: 219, image: "/images/brand-v2/collection-desert-oud.png", en: { name: "Quiet Oud Diffuser", category: "Home Fragrance", description: "A balanced home fragrance of clean woods, sheer rose and soft oud for rooms that feel grounded.", benefits: ["Up to 10 weeks of scent", "Low-maintenance reed format", "Reusable glass vessel"], usage: "Place reeds in the vessel and turn them once weekly for a gentle scent release." }, ar: { name: "فواحة العود الهادئ", category: "عطور منزلية", description: "عطر منزلي متوازن من الأخشاب النظيفة والورد الخفيف والعود الناعم لأجواء أكثر سكينة.", benefits: ["رائحة تدوم حتى 10 أسابيع", "أعواد سهلة الاستخدام", "عبوة زجاجية قابلة لإعادة الاستخدام"], usage: "ضعي الأعواد في العبوة واقلبيها مرة أسبوعياً لنشر العطر بلطف." } }
];
export function getProduct(slug: string) { return products.find((product) => product.slug === slug); }
