export type Product = {
  slug: string; price: number; compareAtPrice?: number; image: string; tag?: "new" | "bestseller";
  en: { name: string; category: string; description: string; benefits: string[]; usage: string };
  ar: { name: string; category: string; description: string; benefits: string[]; usage: string };
};

export const products: Product[] = [
  { slug: "sahar-perfume-oil", price: 189, image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1200&q=85", tag: "bestseller", en: { name: "Sahar Perfume Oil", category: "Fragrance", description: "A warm, luminous perfume oil with amber, soft musk and a trace of saffron. Made to sit close to the skin and unfold slowly.", benefits: ["Alcohol-free concentrated oil", "Travel-friendly roll-on", "Long-wearing, intimate scent"], usage: "Roll gently over pulse points—wrists, neck and behind the ears." }, ar: { name: "زيت عطر سَحَر", category: "عطور", description: "زيت عطري دافئ ومشرق بنفحات العنبر والمسك الناعم ولمسة من الزعفران، يتطور بهدوء على البشرة.", benefits: ["زيت مركز خالٍ من الكحول", "عبوة عملية للسفر", "رائحة حميمة تدوم طويلاً"], usage: "مرّريه برفق على نقاط النبض عند المعصم والرقبة وخلف الأذنين." } },
  { slug: "rose-quartz-ritual-set", price: 149, compareAtPrice: 175, image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=1200&q=85", tag: "new", en: { name: "Rose Quartz Ritual Set", category: "Beauty", description: "A cooling facial roller and sculpting stone for a slow, soothing skincare ritual.", benefits: ["Naturally cooling stone", "Supports facial massage", "Cotton storage pouch included"], usage: "Apply facial oil, then glide outwards from the centre of the face with light pressure." }, ar: { name: "مجموعة طقوس الكوارتز", category: "الجمال", description: "رولر بارد وحجر تدليك لروتين عناية هادئ ومريح للبشرة.", benefits: ["حجر بارد بطبيعته", "مناسب لتدليك الوجه", "يتضمن حقيبة قطنية"], usage: "ضعي زيت الوجه ثم مرّري الأداة بلطف من منتصف الوجه نحو الخارج." } },
  { slug: "quiet-oud-diffuser", price: 219, image: "https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=1200&q=85", en: { name: "Quiet Oud Diffuser", category: "Home", description: "A balanced home fragrance of clean woods, sheer rose and soft oud for rooms that feel grounded.", benefits: ["Up to 10 weeks of scent", "Low-maintenance reed format", "Reusable glass vessel"], usage: "Place reeds in the vessel and turn them once weekly for a gentle scent release." }, ar: { name: "فواحة العود الهادئ", category: "المنزل", description: "عطر منزلي متوازن من الأخشاب النظيفة والورد الخفيف والعود الناعم لأجواء أكثر سكينة.", benefits: ["رائحة تدوم حتى 10 أسابيع", "أعواد سهلة الاستخدام", "عبوة زجاجية قابلة لإعادة الاستخدام"], usage: "ضعي الأعواد في العبوة واقلبيها مرة أسبوعياً لنشر العطر بلطف." } }
];
export function getProduct(slug: string) { return products.find((product) => product.slug === slug); }
