import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import type { Locale } from "@/i18n/config";
import { getBrandContent } from "@/lib/brand-content";
import type { HomepageContentSection } from "@/features/homepage/homepage.repository";
import { HomepageMedia } from "@/components/home/homepage-media";

export function HeroSection({ locale,section }: { locale: Locale;section:HomepageContentSection }) { const {hero}=getBrandContent(locale);const link=section.buttonLink.replace(/^\/en(?=\/)/,`/${locale}`)||"#collections";return <section className="relative min-h-[84svh] overflow-hidden bg-[#17251f] text-[#f7f3e9] lg:grid lg:min-h-[760px] lg:grid-cols-[.82fr_1.18fr]">
  <div className="relative z-10 flex min-h-[84svh] items-end bg-gradient-to-t from-[#17251f] via-[#17251f]/90 to-transparent px-7 py-16 lg:min-h-[760px] lg:items-center lg:bg-[#17251f] lg:px-[clamp(3rem,7vw,8rem)]"><div className="max-w-5xl animate-rise"><p className="text-xs font-medium uppercase tracking-[.28em] text-[#d2ad66]">{hero.eyebrow}</p><h1 className="font-display mt-7 max-w-5xl text-[clamp(3.8rem,7vw,7.8rem)] font-medium leading-[.84] tracking-[-.035em]">{section.title}</h1><p className="mt-8 max-w-xl text-base font-light leading-8 text-white/68 lg:text-lg">{section.subtitle||hero.body}</p><div className="mt-10 flex flex-wrap gap-4"><Link href={link} className="inline-flex min-h-12 items-center gap-3 bg-[#f7f3e9] px-6 text-sm font-medium text-[#17251f] transition hover:bg-[#d2ad66]">{section.buttonText||hero.primary}<ArrowUpRight size={16}/></Link><Link href="#story" className="inline-flex min-h-12 items-center border border-white/28 px-6 text-sm font-medium text-white transition hover:border-white hover:bg-white/8">{hero.secondary}</Link></div></div></div>
  <div className="absolute inset-0 lg:relative"><HomepageMedia section={section} alt={section.title} priority className="hero-slow-zoom"/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(23,37,31,.05),rgba(23,37,31,.65))] lg:bg-[linear-gradient(90deg,rgba(23,37,31,.45),transparent_22%)] rtl:lg:bg-[linear-gradient(270deg,rgba(23,37,31,.45),transparent_22%)]"/><div className="absolute bottom-6 end-6 hidden border border-white/28 bg-black/15 px-5 py-3 text-[10px] uppercase tracking-[.22em] text-white/80 backdrop-blur-md lg:block">Riyadh · Saudi Arabia</div></div>
</section>; }
