import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import type { Locale } from "@/i18n/config";

export function SiteFooter({locale}:{locale:Locale}) {
  const home=`/${locale}`;
  const copy=locale==="ar"?{line:"عطور منزلية عربية فاخرة صُممت لطقوس البيت ولحظات الترحيب.",shop:"اكتشفوا",about:"نُـورا",fragrance:"العطور",collections:"المجموعات",gifts:"الهدايا",story:"قصتنا",contact:"تواصلوا معنا",delivery:"التوصيل والإرجاع",note:"رسائل من نُـورا",noteBody:"حكايات عطرية وإصدارات جديدة تصل بهدوء إلى بريدكم.",join:"انضموا إلى القائمة",country:"المملكة العربية السعودية · ر.س",rights:"© 2026 NURAA. جميع الحقوق محفوظة."}:{line:"Luxury Arabian home fragrance, composed for the rituals and welcomes that shape a home.",shop:"Discover",about:"NURAA",fragrance:"Fragrance",collections:"Collections",gifts:"Gifts",story:"Our story",contact:"Contact us",delivery:"Delivery & returns",note:"Notes from NURAA",noteBody:"Scent stories and new releases, delivered quietly to your inbox.",join:"Join the list",country:"Saudi Arabia · SAR",rights:"© 2026 NURAA. All rights reserved."};
  return <footer className="bg-[#352219] text-[#FBF6EC]"><div className="mx-auto max-w-7xl px-6 py-16 lg:px-8 lg:py-20">
    <div className="grid gap-14 border-b border-white/12 pb-16 lg:grid-cols-[1.45fr_.75fr_.75fr_1.2fr]"><div><Link href={home} className="font-display text-4xl font-semibold tracking-[.2em]">NURAA</Link><p className="mt-5 max-w-sm text-sm leading-7 text-white/55">{copy.line}</p><a href="https://www.instagram.com/" aria-label="Instagram" className="mt-7 grid size-10 place-items-center rounded-full border border-white/20 text-[10px] font-semibold tracking-[.08em] transition hover:border-[#D5AE68] hover:text-[#D5AE68]">IG</a></div>
      <div><h3 className="text-[10px] uppercase tracking-[.22em] text-[#D5AE68]">{copy.shop}</h3><div className="mt-5 space-y-3 text-sm text-white/60"><Link className="block hover:text-white" href={`${home}/products#catalog`}>{copy.fragrance}</Link><Link className="block hover:text-white" href={`${home}#collections`}>{copy.collections}</Link><Link className="block hover:text-white" href={`${home}#gifts`}>{copy.gifts}</Link></div></div>
      <div><h3 className="text-[10px] uppercase tracking-[.22em] text-[#D5AE68]">{copy.about}</h3><div className="mt-5 space-y-3 text-sm text-white/60"><Link className="block hover:text-white" href={`${home}#story`}>{copy.story}</Link><Link className="block hover:text-white" href={`${home}#gifts`}>{copy.gifts}</Link><a className="block hover:text-white" href="mailto:hello@nuraa.sa">{copy.contact}</a><Link className="block hover:text-white" href={`${home}/products`}>{copy.delivery}</Link></div></div>
      <div><h3 className="font-display text-3xl">{copy.note}</h3><p className="mt-4 max-w-sm text-sm leading-6 text-white/55">{copy.noteBody}</p><a href="mailto:hello@nuraa.sa?subject=NURAA%20Newsletter" className="mt-7 inline-flex items-center gap-2 border-b border-[#D5AE68] pb-2 text-xs uppercase tracking-[.16em]">{copy.join}<ArrowUpRight size={14}/></a></div>
    </div><div className="flex flex-col gap-3 pt-6 text-[10px] uppercase tracking-[.15em] text-white/40 sm:flex-row sm:justify-between"><span>{copy.country}</span><span>{copy.rights}</span></div>
  </div></footer>;
}
