import "server-only";
import { db } from "@/lib/db";

export type RangeKey="today"|"7d"|"30d";
export function parseRange(value?:string):RangeKey{return value==="7d"||value==="30d"?value:"today"}
function riyadhStart(days:number){const now=new Date();const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Riyadh",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(now);const n=(t:string)=>Number(parts.find(p=>p.type===t)?.value);const today=Date.UTC(n("year"),n("month")-1,n("day"))-3*3600000;return new Date(today-(days-1)*86400000)}
function rangeStart(range:RangeKey){return riyadhStart(range==="today"?1:range==="7d"?7:30)}

export async function getDashboardData(range:RangeKey){const start=rangeStart(range);const [sessions,purchases,revenue,productCount,events]=await Promise.all([
  db.analyticsEvent.findMany({where:{eventType:"PAGE_VIEW",occurredAt:{gte:start}},distinct:["sessionId"],select:{sessionId:true}}),
  db.analyticsEvent.findMany({where:{eventType:"PURCHASE",occurredAt:{gte:start}},distinct:["orderReference"],select:{orderReference:true}}),
  db.analyticsEvent.aggregate({where:{eventType:"PURCHASE",occurredAt:{gte:start}},_sum:{revenue:true}}),
  db.product.count({where:{deletedAt:null}}),
  db.analyticsEvent.findMany({where:{occurredAt:{gte:start}},select:{eventType:true,occurredAt:true,revenue:true,sessionId:true,trafficSource:{select:{channel:true}},product:{select:{id:true,slug:true,translations:{where:{locale:"EN"},select:{name:true}}}}},orderBy:{occurredAt:"asc"}})
]);
const visitors=sessions.length,orders=purchases.filter(x=>x.orderReference).length,sales=Number(revenue._sum.revenue??0);const days=range==="today"?1:range==="7d"?7:30;
const trend=new Map<string,{label:string;revenue:number;orders:number;visitors:Set<string>}>();for(let i=0;i<days;i++){const date=new Date(start.getTime()+i*86400000);const key=date.toISOString().slice(0,10);trend.set(key,{label:range==="today"?"Today":date.toLocaleDateString("en",{month:"short",day:"numeric",timeZone:"Asia/Riyadh"}),revenue:0,orders:0,visitors:new Set()})}
const channels=new Map<string,{visits:Set<string>;orders:number;revenue:number}>();const products=new Map<string,{id:string;name:string;slug:string;views:number;carts:number;orders:number;revenue:number}>();
for(const event of events){const day=event.occurredAt.toLocaleDateString("en-CA",{timeZone:"Asia/Riyadh"});const t=trend.get(day);if(t){if(event.eventType==="PAGE_VIEW")t.visitors.add(event.sessionId);if(event.eventType==="PURCHASE"){t.orders++;t.revenue+=Number(event.revenue??0)}}const channel=event.trafficSource?.channel??"DIRECT";if(!channels.has(channel))channels.set(channel,{visits:new Set(),orders:0,revenue:0});const c=channels.get(channel)!;if(event.eventType==="PAGE_VIEW")c.visits.add(event.sessionId);if(event.eventType==="PURCHASE"){c.orders++;c.revenue+=Number(event.revenue??0)}if(event.product){if(!products.has(event.product.id))products.set(event.product.id,{id:event.product.id,name:event.product.translations[0]?.name??event.product.slug,slug:event.product.slug,views:0,carts:0,orders:0,revenue:0});const p=products.get(event.product.id)!;if(event.eventType==="PRODUCT_VIEW")p.views++;if(event.eventType==="ADD_TO_CART")p.carts++;if(event.eventType==="PURCHASE"){p.orders++;p.revenue+=Number(event.revenue??0)}}}
return {range,kpis:{revenue:sales,orders,visitors,conversion:visitors?orders/visitors*100:0,aov:orders?sales/orders:0,products:productCount},trend:[...trend.values()].map(x=>({label:x.label,revenue:x.revenue,orders:x.orders,visitors:x.visitors.size})),channels:["TIKTOK","FACEBOOK","GOOGLE","DIRECT"].map(channel=>{const c=channels.get(channel);const visits=c?.visits.size??0;const channelOrders=c?.orders??0;return{channel,visits,orders:channelOrders,revenue:c?.revenue??0,conversion:visits?channelOrders/visits*100:0}}),funnel:{pageViews:events.filter(x=>x.eventType==="PAGE_VIEW").length,productViews:events.filter(x=>x.eventType==="PRODUCT_VIEW").length,addToCarts:events.filter(x=>x.eventType==="ADD_TO_CART").length,checkoutStarts:events.filter(x=>x.eventType==="CHECKOUT_START").length,purchases:events.filter(x=>x.eventType==="PURCHASE").length},topProducts:[...products.values()].sort((a,b)=>b.revenue-a.revenue||b.views-a.views).slice(0,6)}
}
